name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          extensions: mbstring, xml, intl, pdo, pdo_mysql, sqlite
          coverage: xdebug
          
      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress
          # Установка инструментов анализа кода
          composer require --dev squizlabs/php_codesniffer phpstan/phpstan
          
      - name: Create reports directory
        run: mkdir -p reports
      
      - name: Setup environment
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env
          
      - name: Run Linting
        run: make lint

      - name: Run Tests
        run: make test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}