name: CI

on:
  - pull_request
  - push
  
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          
      - name: Install Node.js (v18 LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress
      
      - name: Install npm dependencies
        run: npm install
      
      - name: Build assets (with CI=false)
        run: CI=false npm run build  # Важно!
          
      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}