name: SonarCloud
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          cp .env.example .env
          php artisan key:generate
          
      - name: Generate coverage report
        run: |
          mkdir -p tests/Unit  # Создаем директорию если отсутствует
          vendor/bin/phpunit --coverage-clover coverage.xml
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.php.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**/*
            -Dsonar.cpd.exclusions=tests/**/*