name: SonarCloud Scan
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Install dependencies
        run: composer install

      - name: Generate coverage reports
        run: |
          mkdir -p reports
          vendor/bin/phpunit --coverage-clover reports/coverage.xml --log-junit reports/junit.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}